# Ansible inventory created from ['sr+bgp.yml', 'package:topology-defaults.yml']
#
---
csr:
  hosts:
    c1:
      ansible_host: 192.168.121.101
      id: 1
    e1:
      ansible_host: 192.168.121.103
      id: 3
eos:
  hosts:
    c2:
      ansible_host: 192.168.121.102
      id: 2
    e2:
      ansible_host: 192.168.121.104
      id: 4
iosv:
  hosts:
    x1:
      ansible_host: 192.168.121.105
      id: 5
    x2:
      ansible_host: 192.168.121.106
      id: 6
