# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
frr:
  hosts:
    c1:
      ansible_host: clab-LocPref-Prepend-c1
      id: 1
    c2:
      ansible_host: clab-LocPref-Prepend-c2
      id: 2
    pe1:
      ansible_host: clab-LocPref-Prepend-pe1
      id: 4
    pe2:
      ansible_host: clab-LocPref-Prepend-pe2
      id: 5
    pe3:
      ansible_host: clab-LocPref-Prepend-pe3
      id: 6
    x1:
      ansible_host: clab-LocPref-Prepend-x1
      id: 3
