# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: arista/veos
isis:
  area: 49.0001
  ipv4: true
  ipv6: true
  type: level-2
links:
- ifindex: 1
  ifname: Ethernet1
  linkindex: 2
  name: c2 -> e1
  neighbors:
    e1:
      ifname: GigabitEthernet3
  remote_id: 3
  remote_ifindex: 3
  type: p2p
  unnumbered: true
- ifindex: 2
  ifname: Ethernet2
  linkindex: 4
  name: c2 -> e2
  neighbors:
    e2:
      ifname: Ethernet2
  remote_id: 4
  remote_ifindex: 2
  type: p2p
  unnumbered: true
loopback:
  ipv4: 10.0.0.2/32
  ipv6: 2001:db8:cafe:2::1/64
mgmt:
  ifname: Management1
  ipv4: 192.168.121.102
  mac: 08-4F-A9-00-00-02
module:
- sr
- isis
