# Ansible inventory created from ['sr+bgp.yml', 'package:topology-defaults.yml']
#
---
bgp:
  as: 65000
  neighbors:
  - as: 65000
    ipv4: 10.0.0.4
    name: e2
    type: ibgp
  - as: 65001
    ipv4: 10.1.0.18
    name: x1
    type: ebgp
  next_hop_self: true
box: cisco/csr1000v
isis:
  area: 49.0001
  ipv4: true
  type: level-2
links:
- ifindex: 2
  ifname: GigabitEthernet2
  ipv4: 10.1.0.2/30
  linkindex: 1
  name: e1 -> c1
  neighbors:
    c1:
      ifname: GigabitEthernet2
      ipv4: 10.1.0.1/30
  remote_id: 1
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: GigabitEthernet3
  ipv4: 10.1.0.6/30
  linkindex: 2
  name: e1 -> c2
  neighbors:
    c2:
      ifname: Ethernet1
      ipv4: 10.1.0.5/30
  remote_id: 2
  remote_ifindex: 1
  type: p2p
- ifindex: 4
  ifname: GigabitEthernet4
  ipv4: 10.1.0.17/30
  linkindex: 5
  name: e1 -> x1
  neighbors:
    x1:
      ifname: GigabitEthernet0/1
      ipv4: 10.1.0.18/30
  remote_id: 5
  remote_ifindex: 1
  role: external
  type: p2p
loopback:
  ipv4: 10.0.0.3/32
mgmt:
  ifname: GigabitEthernet1
  ipv4: 192.168.121.103
  mac: 08-4F-A9-00-00-03
module:
- sr
- isis
- bgp
