# Ansible inventory created from ['unnumbered.yml', '/home/pipi/Net101/tools/topology-defaults.yml']
#
---
box: juniper/vsrx3
links:
- ifindex: 0
  ifname: ge-0/0/0
  linkindex: 3
  name: j_vsrx -> c_nxos
  neighbors:
    c_nxos:
      ifname: Ethernet1/3
  remote_id: 1
  remote_ifindex: 3
  role: core
  type: p2p
  unnumbered: true
- ifindex: 1
  ifname: ge-0/0/1
  linkindex: 4
  name: j_vsrx -> a_eos
  neighbors:
    a_eos:
      ifname: Ethernet2
  remote_id: 3
  remote_ifindex: 2
  role: core
  type: p2p
  unnumbered: true
- ifindex: 2
  ifname: ge-0/0/2
  linkindex: 6
  name: j_vsrx -> c_csr
  neighbors:
    c_csr:
      ifname: GigabitEthernet4
  remote_id: 2
  remote_ifindex: 4
  role: core
  type: p2p
  unnumbered: true
loopback:
  ipv4: 10.0.0.4/32
mgmt:
  ifname: fxp0
  ipv4: 192.168.121.104
  mac: 08-4F-A9-00-00-04
module:
- ospf
