# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: cisco/csr1000v
links:
- ifindex: 2
  ifname: GigabitEthernet2
  ipv4: 10.1.0.2/30
  linkindex: 1
  name: rtr -> c1
  neighbors:
    c1:
      ifname: GigabitEthernet2
      ipv4: 10.1.0.1/30
  remote_id: 2
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: GigabitEthernet3
  ipv4: 10.1.0.6/30
  linkindex: 2
  name: rtr -> c2
  neighbors:
    c2:
      ifname: GigabitEthernet2
      ipv4: 10.1.0.5/30
  remote_id: 3
  remote_ifindex: 2
  type: p2p
- bridge: lan-unnumbered_3
  ifindex: 4
  ifname: GigabitEthernet4
  ipv4: 172.16.0.1/24
  linkindex: 3
  neighbors: {}
  type: stub
loopback:
  ipv4: 10.0.0.1/32
mgmt:
  ifname: GigabitEthernet1
  ipv4: 192.168.121.101
  mac: 08-4F-A9-00-00-01
