# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: arista/veos
isis:
  area: 49.0001
  ipv4: true
  ipv6: true
  type: level-2
links:
- ifindex: 1
  ifname: Ethernet1
  linkindex: 3
  name: e2 -> c1
  neighbors:
    c1:
      ifname: GigabitEthernet3
  remote_id: 1
  remote_ifindex: 3
  type: p2p
  unnumbered: true
- ifindex: 2
  ifname: Ethernet2
  linkindex: 4
  name: e2 -> c2
  neighbors:
    c2:
      ifname: Ethernet2
  remote_id: 2
  remote_ifindex: 2
  type: p2p
  unnumbered: true
- bridge: sr-mpls-sid_6
  ifindex: 3
  ifname: Ethernet3
  ipv4: 172.16.1.4/24
  linkindex: 6
  neighbors: {}
  type: stub
loopback:
  ipv4: 10.0.0.4/32
  ipv6: 2001:db8:cafe:4::1/64
mgmt:
  ifname: Management1
  ipv4: 192.168.121.104
  mac: 08-4F-A9-00-00-04
module:
- sr
- isis
