# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: cisco/csr1000v
isis:
  area: 49.0001
  ipv4: true
  ipv6: true
  type: level-2
links:
- ifindex: 2
  ifname: GigabitEthernet2
  linkindex: 1
  name: c1 -> e1
  neighbors:
    e1:
      ifname: GigabitEthernet2
  remote_id: 3
  remote_ifindex: 2
  type: p2p
  unnumbered: true
- ifindex: 3
  ifname: GigabitEthernet3
  linkindex: 3
  name: c1 -> e2
  neighbors:
    e2:
      ifname: Ethernet1
  remote_id: 4
  remote_ifindex: 1
  type: p2p
  unnumbered: true
loopback:
  ipv4: 10.0.0.1/32
  ipv6: 2001:db8:cafe:1::1/64
mgmt:
  ifname: GigabitEthernet1
  ipv4: 192.168.121.101
  mac: 08-4F-A9-00-00-01
module:
- sr
- isis
