# Ansible inventory created from ['topology-2igp.yml', '../../tools/topology-defaults.yml']
#
---
igp:
- ospf
- eigrp
links:
- ifindex: 2
  ifname: GigabitEthernet2
  ip: 10.1.0.1/30
  neighbors:
    e1:
      ifname: GigabitEthernet0/1
      ip: 10.1.0.2/30
  remote_id: 1
  remote_ifindex: 1
  type: p2p
- bandwidth: 1000
  ifindex: 3
  ifname: GigabitEthernet3
  ip: 10.1.0.5/30
  neighbors:
    e2:
      ifname: GigabitEthernet0/1
      ip: 10.1.0.6/30
  remote_id: 2
  remote_ifindex: 1
  type: p2p
loopback: 10.0.0.3
mgmt_if: GigabitEthernet1
mgmt_ip: 192.168.121.103
mgmt_mac: 08-4F-A9-00-00-03
