# Ansible inventory created from ['topology-2igp.yml', '../../tools/topology-defaults.yml']
#
---
csr:
  hosts:
    pe1:
      ansible_host: 192.168.121.103
      id: 3
iosv:
  hosts:
    e1:
      ansible_host: 192.168.121.101
      id: 1
    e2:
      ansible_host: 192.168.121.102
      id: 2
