# Ansible inventory created from ['sr+bgp.yml', 'package:topology-defaults.yml']
#
---
bgp:
  as: 65000
  neighbors:
  - as: 65000
    ipv4: 10.0.0.3
    name: e1
    type: ibgp
  - as: 65002
    ipv4: 10.1.0.22
    name: x2
    type: ebgp
  next_hop_self: true
box: arista/veos
isis:
  area: 49.0001
  ipv4: true
  type: level-2
links:
- ifindex: 1
  ifname: Ethernet1
  ipv4: 10.1.0.10/30
  linkindex: 3
  name: e2 -> c1
  neighbors:
    c1:
      ifname: GigabitEthernet3
      ipv4: 10.1.0.9/30
  remote_id: 1
  remote_ifindex: 3
  type: p2p
- ifindex: 2
  ifname: Ethernet2
  ipv4: 10.1.0.14/30
  linkindex: 4
  name: e2 -> c2
  neighbors:
    c2:
      ifname: Ethernet2
      ipv4: 10.1.0.13/30
  remote_id: 2
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: Ethernet3
  ipv4: 10.1.0.21/30
  linkindex: 6
  name: e2 -> x2
  neighbors:
    x2:
      ifname: GigabitEthernet0/1
      ipv4: 10.1.0.22/30
  remote_id: 6
  remote_ifindex: 1
  role: external
  type: p2p
loopback:
  ipv4: 10.0.0.4/32
mgmt:
  ifname: Management1
  ipv4: 192.168.121.104
  mac: 08-4F-A9-00-00-04
module:
- sr
- isis
- bgp
