# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
bgp:
  advertise_loopback: true
  as: 65000
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65000
    ipv4: 10.0.0.5
    name: pe2
    type: ibgp
  - as: 65000
    ipv4: 10.0.0.6
    name: pe3
    type: ibgp
  - as: 65100
    ifindex: 1
    ipv4: 10.1.0.1
    name: c1
    type: ebgp
  next_hop_self: true
box: frrouting/frr:v7.5.0
hostname: clab-LocPref-Prepend-pe1
kind: linux
links:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.2/30
  linkindex: 1
  name: pe1 -> c1
  neighbors:
    c1:
      ifname: eth1
      ipv4: 10.1.0.1/30
  remote_id: 1
  remote_ifindex: 1
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 10.1.0.13/30
  linkindex: 4
  name: pe1 -> pe2
  neighbors:
    pe2:
      ifname: eth2
      ipv4: 10.1.0.14/30
  remote_id: 5
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv4: 10.1.0.17/30
  linkindex: 5
  name: pe1 -> pe3
  neighbors:
    pe3:
      ifname: eth1
      ipv4: 10.1.0.18/30
  remote_id: 6
  remote_ifindex: 1
  type: p2p
loopback:
  ipv4: 10.0.0.4/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.104
  mac: 08-4F-A9-00-00-04
module:
- bgp
- ospf
