# Ansible inventory created from ['unnumbered.yml', '/home/pipi/Net101/tools/topology-defaults.yml']
#
---
box: arista/veos
links:
- ifindex: 1
  ifname: Ethernet1
  linkindex: 1
  name: a_eos -> c_nxos
  neighbors:
    c_nxos:
      ifname: Ethernet1/1
  remote_id: 1
  remote_ifindex: 1
  role: core
  type: p2p
  unnumbered: true
- ifindex: 2
  ifname: Ethernet2
  linkindex: 4
  name: a_eos -> j_vsrx
  neighbors:
    j_vsrx:
      ifname: ge-0/0/1
  remote_id: 4
  remote_ifindex: 1
  role: core
  type: p2p
  unnumbered: true
- ifindex: 3
  ifname: Ethernet3
  linkindex: 5
  name: a_eos -> c_csr
  neighbors:
    c_csr:
      ifname: GigabitEthernet3
  remote_id: 2
  remote_ifindex: 3
  role: core
  type: p2p
  unnumbered: true
loopback:
  ipv4: 10.0.0.3/32
mgmt:
  ifname: Management1
  ipv4: 192.168.121.103
  mac: 08-4F-A9-00-00-03
module:
- ospf
