# Ansible inventory created from ['topology.yml', '../../tools/topology-defaults.yml']
#
---
csr:
  hosts:
    pe1:
      ansible_host: 192.168.121.101
      id: 1
iosv:
  hosts:
    p1:
      ansible_host: 192.168.121.102
      id: 2
    p2:
      ansible_host: 192.168.121.103
      id: 3
    pe2:
      ansible_host: 192.168.121.104
      id: 4
