# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: cisco/csr1000v
links:
- ifindex: 2
  ifname: GigabitEthernet2
  ipv4: 10.1.0.6/30
  linkindex: 2
  name: r3 -> r1
  neighbors:
    r1:
      ifname: GigabitEthernet3
      ipv4: 10.1.0.5/30
  remote_id: 1
  remote_ifindex: 3
  type: p2p
- bridge: lan-unnumbered_5
  ifindex: 3
  ifname: GigabitEthernet3
  ipv4: 172.16.2.3/24
  linkindex: 5
  neighbors: {}
  type: stub
loopback:
  ipv4: 10.0.0.3/32
mgmt:
  ifname: GigabitEthernet1
  ipv4: 192.168.121.103
  mac: 08-4F-A9-00-00-03
