# Ansible inventory created from ['topology.yml', '../tools/topology-defaults.yml']
#
---
eos:
  hosts:
    eos:
      ansible_host: 192.168.121.101
      id: 1
      links:
      - bridge: LAN_1
        ifindex: 1
        ifname: Ethernet1
        ip: 172.16.0.1/24
        neighbors:
          ios:
            ifname: GigabitEthernet0/1
            ip: 172.16.0.3/24
          nxos:
            ifname: Ethernet1/1
            ip: 172.16.0.2/24
        type: lan
      - bridge: LAN_2
        ifindex: 2
        ifname: Ethernet2
        ip: 172.16.1.1/24
        neighbors:
          ios:
            ifname: GigabitEthernet0/2
            ip: 172.16.1.3/24
          nxos:
            ifname: Ethernet1/2
            ip: 172.16.1.2/24
        type: lan
      loopback: 10.0.0.1
      mgmt_if: Management1
      mgmt_ip: 192.168.121.101
      mgmt_mac: 08-4F-A9-00-00-01
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_ssh_pass: vagrant
    ansible_user: vagrant
iosv:
  hosts:
    ios:
      ansible_host: 192.168.121.103
      id: 3
      links:
      - bridge: LAN_1
        ifindex: 1
        ifname: GigabitEthernet0/1
        ip: 172.16.0.3/24
        neighbors:
          eos:
            ifname: Ethernet1
            ip: 172.16.0.1/24
          nxos:
            ifname: Ethernet1/1
            ip: 172.16.0.2/24
        type: lan
      - bridge: LAN_2
        ifindex: 2
        ifname: GigabitEthernet0/2
        ip: 172.16.1.3/24
        neighbors:
          eos:
            ifname: Ethernet2
            ip: 172.16.1.1/24
          nxos:
            ifname: Ethernet1/2
            ip: 172.16.1.2/24
        type: lan
      loopback: 10.0.0.3
      mgmt_if: GigabitEthernet0/0
      mgmt_ip: 192.168.121.103
      mgmt_mac: 08-4F-A9-00-00-03
  vars:
    ansible_become_method: enable
    ansible_become_password: vagrant
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_pass: vagrant
    ansible_user: vagrant
nxos:
  hosts:
    nxos:
      ansible_host: 192.168.121.102
      id: 2
      links:
      - bridge: LAN_1
        ifindex: 1
        ifname: Ethernet1/1
        ip: 172.16.0.2/24
        neighbors:
          eos:
            ifname: Ethernet1
            ip: 172.16.0.1/24
          ios:
            ifname: GigabitEthernet0/1
            ip: 172.16.0.3/24
        type: lan
      - bridge: LAN_2
        ifindex: 2
        ifname: Ethernet1/2
        ip: 172.16.1.2/24
        neighbors:
          eos:
            ifname: Ethernet2
            ip: 172.16.1.1/24
          ios:
            ifname: GigabitEthernet0/2
            ip: 172.16.1.3/24
        type: lan
      loopback: 10.0.0.2
      mgmt_if: mgmt0
      mgmt_ip: 192.168.121.102
      mgmt_mac: 08-4F-A9-00-00-02
  vars:
    ansible_connection: network_cli
    ansible_network_os: nxos
    ansible_ssh_pass: vagrant
    ansible_user: vagrant
