# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
csr:
  hosts:
    c_csr:
      ansible_host: 192.168.121.102
      id: 2
eos:
  hosts:
    a_eos:
      ansible_host: 192.168.121.103
      id: 3
nxos:
  hosts:
    c_nxos:
      ansible_host: 192.168.121.101
      id: 1
vsrx:
  hosts:
    j_vsrx:
      ansible_host: 192.168.121.104
      id: 4
