# Ansible inventory created from ['sr+bgp.yml', 'package:topology-defaults.yml']
#
---
bgp:
  as: 65002
  neighbors:
  - as: 65000
    ipv4: 10.1.0.21
    name: e2
    type: ebgp
  next_hop_self: true
box: cisco/iosv
links:
- ifindex: 1
  ifname: GigabitEthernet0/1
  ipv4: 10.1.0.22/30
  linkindex: 6
  name: x2 -> e2
  neighbors:
    e2:
      ifname: Ethernet3
      ipv4: 10.1.0.21/30
  remote_id: 4
  remote_ifindex: 3
  role: external
  type: p2p
- bgp:
    advertise: true
  bridge: sr-mpls-bgp_8
  ifindex: 2
  ifname: GigabitEthernet0/2
  ipv4: 172.16.1.6/24
  linkindex: 8
  neighbors: {}
  type: stub
loopback:
  ipv4: 10.0.0.6/32
mgmt:
  ifname: GigabitEthernet0/0
  ipv4: 192.168.121.106
  mac: 08-4F-A9-00-00-06
module:
- bgp
