# Ansible inventory created from ['unnumbered.yml', '/home/pipi/Net101/tools/topology-defaults.yml']
#
---
ansible_become_method: enable
ansible_become_password: vagrant
ansible_connection: network_cli
ansible_network_os: ios
ansible_ssh_pass: vagrant
ansible_user: vagrant
