# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
csr:
  hosts:
    c1:
      ansible_host: 192.168.121.102
      id: 2
    c2:
      ansible_host: 192.168.121.103
      id: 3
    rtr:
      ansible_host: 192.168.121.101
      id: 1
