# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
csr:
  hosts:
    r1:
      ansible_host: 192.168.121.101
      id: 1
    r2:
      ansible_host: 192.168.121.102
      id: 2
