# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
bgp:
  advertise_loopback: true
  as: 65000
  community:
    ebgp:
    - standard
    ibgp:
    - standard
    - extended
  ipv4: true
  neighbors:
  - as: 65000
    ipv4: 10.0.0.4
    name: pe1
    type: ibgp
  - as: 65000
    ipv4: 10.0.0.6
    name: pe3
    type: ibgp
  - as: 65101
    ifindex: 1
    ipv4: 10.1.0.5
    name: c2
    type: ebgp
  next_hop_self: true
box: frrouting/frr:v7.5.0
hostname: clab-LocPref-Prepend-pe2
kind: linux
links:
- ifindex: 1
  ifname: eth1
  ipv4: 10.1.0.6/30
  linkindex: 2
  name: pe2 -> c2
  neighbors:
    c2:
      ifname: eth1
      ipv4: 10.1.0.5/30
  remote_id: 2
  remote_ifindex: 1
  role: external
  type: p2p
- ifindex: 2
  ifname: eth2
  ipv4: 10.1.0.14/30
  linkindex: 4
  name: pe2 -> pe1
  neighbors:
    pe1:
      ifname: eth2
      ipv4: 10.1.0.13/30
  remote_id: 4
  remote_ifindex: 2
  type: p2p
- ifindex: 3
  ifname: eth3
  ipv4: 10.1.0.21/30
  linkindex: 6
  name: pe2 -> pe3
  neighbors:
    pe3:
      ifname: eth2
      ipv4: 10.1.0.22/30
  remote_id: 6
  remote_ifindex: 2
  type: p2p
loopback:
  ipv4: 10.0.0.5/32
mgmt:
  ifname: eth0
  ipv4: 192.168.121.105
  mac: 08-4F-A9-00-00-05
module:
- bgp
- ospf
