# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
box: cisco/csr1000v
isis:
  area: 49.0001
  ipv4: true
  ipv6: true
  type: level-2
links:
- ifindex: 2
  ifname: GigabitEthernet2
  linkindex: 1
  name: e1 -> c1
  neighbors:
    c1:
      ifname: GigabitEthernet2
  remote_id: 1
  remote_ifindex: 2
  type: p2p
  unnumbered: true
- ifindex: 3
  ifname: GigabitEthernet3
  linkindex: 2
  name: e1 -> c2
  neighbors:
    c2:
      ifname: Ethernet1
  remote_id: 2
  remote_ifindex: 1
  type: p2p
  unnumbered: true
- bridge: sr-mpls-sid_5
  ifindex: 4
  ifname: GigabitEthernet4
  ipv4: 172.16.0.3/24
  linkindex: 5
  neighbors: {}
  type: stub
loopback:
  ipv4: 10.0.0.3/32
  ipv6: 2001:db8:cafe:3::1/64
mgmt:
  ifname: GigabitEthernet1
  ipv4: 192.168.121.103
  mac: 08-4F-A9-00-00-03
module:
- sr
- isis
